name: Run Screener Hourly

# Schedule: Run at the start of every hour (UTC)
on:
  workflow_dispatch:    # 👈 manual trigger
  schedule:
    - cron: '10 9-14 * * 1-5'  # 9:10 AM to 3:10 PM IST (Mon–Fri). UTC 3:40 is 9:10am IST

jobs:
  run-screener:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run screener script
        env:
          # Put your Google service account JSON as a secret in GitHub (see Step 4)
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          TZ: "Asia/Kolkata"
          LOCAL_TIME: "12:00"
        run: python screener_1h.py
